### ISSUE TITLE
Scheduled scans periodically fail because of missing Tranco list

### ISSUE THREAD

**Issue by ghostwords** [EFForg/badger-sett#90]
Seems to happen fairly frequently at this point.

```
Running scan in Docker...
Traceback (most recent call last):
  File "/home/user/./crawler.py", line 1203, in <module>
    domains = crawler.get_sitelist()
              ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/./crawler.py", line 897, in get_sitelist
    domains = Tranco(cache_dir=tempfile.gettempdir()).list(TRANCO_VERSION).top()
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ ^
  File "/home/user/.local/lib/python3.12/site-packages/tranco/tranco.py", line 65, in list 
    top_list_text = self._download_zip_file(list_id)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/.local/lib/python3.12/site-packages/tranco/tranco.py", line 106, in _download_zip_file
    raise AttributeError("The daily list for this date is currently unavailable.")
AttributeError: The daily list for this date is currently unavailable.
Scan failed. See log.txt for details.
```

**Comment by ghostwords** [comment]
Fixed by 44b99ec3d2baccd29c0aab8a036c254c729ee640.

**Comment by BatMiles** [comment]
I've updated tranco to v0.8.1 and am still seeing this error.

**Comment by ghostwords** [comment]
Tranco will still produce the error, it's just that I added a workaround where Badger Sett will try progressively older dates until it finds a date that works or it runs out of attempts: https://github.com/EFForg/badger-sett/blob/164b08a655009eb2544593f989eadc2c279efa72/crawler.py#L881-L900
